### ISSUE TITLE
El comando da.conectar no funciona

### ISSUE THREAD

**Issue by OriolCobo** [undesconocido/Datum#1]
No consigo que el comando da.conectar funcione, una vez sepa como añadirlo se solucionara este issue.

**Comment by undesconocido** [comment]
Conseguiste añadir el comando al final? Si no has conseguido levantarlo dímelo y esta tarde lo cerramos.

**Comment by OriolCobo** [comment]
El comando sige sin ir pero sin lo que hicistes en develop no se si ira, porque empeze a currar antes de que hicieras cambios y no se si en git puedo pillar los cambos de esa branch pero manteniendo lo mio. Por eso he hecho el pull request.

**Comment by OriolCobo** [comment]
Funcionando, al hacer pull de la rama de develop.
